[tools]
antigravity-cli = "latest"
bun = "1.4.2"
chezmoi = "latest"
codex = "latest"
node = "latest"
"npm:@opencode/cli" = { version = "latest", allow_builds = ["@opencode/cli"], allow_low_downloads = true }
"npm:@earendil-works/pi-coding-agent" = "latest"
pnpm = "latest"
usage = "latest"

[settings.upgrade]
auto_prune = false
